### PR TITLE
Design refresh

### LINKED ISSUE #75: File Upload Types design changes
In this comment https://github.com/awesomemotive/file-upload-types/issues/53#issuecomment-1496729473 @mattbrett suggested how defining file type by sample should look and behave, but he also provided a bit deeper interface redesign. This ticket is to handle the redesign part and not block File By Sample functionality (which is handled in #64 )

Figma file: https://www.figma.com/design/ML5HOsdI9xsVZNEPHkGybY/File-Upload-Types?node-id=0-1&t=zawMaVMDwZ6XQ58V-0

Screencast: https://a.supportally.com/v/xhxCgt

### PR DESCRIPTION
**Pull request by kkarpieszuk**
Fixes #75

### CODE REVIEW

**Review by wppunk — APPROVED** [review]
@kkarpieszuk thanks for your changes. LGTM 👍

**Comment by mattbrett** [comment]
@kkarpieszuk This looks really good. Great job implementing the design changes. 👏🏻

Just a few things I want to take care of, and it's basically removing our colour overrides in favour of WP defaults. That was a big part of this refresh, but we still have our own colours in some areas. [Here's a screencast](https://a.supportally.com/v/SM7bjf) showing what I'd like it to look like. I'm aware this means the page will inherit WP admin theme colours if they change, and that's fine.

- [x] Remove border, box-shadow, and color overrides for all input fields, including checkboxes.
- [x] Remove the color override on the link in the upload area.
- [x] Remove the light grey background colour of the fields in the bottom section.
- [x] Can we left align the text in the tooltip?

**Comment by kkarpieszuk** [comment]
Thanks @mattbrett and done. Would you check this one more time?

**Comment by mattbrett** [comment]
@kkarpieszuk Changes look good, only one small thing left. When there's just one manual row, you're using a filter to make the trash button look disabled, but it doesn't really look disabled to me. There's still a hover state on it, and it's too dark to look disabled. If we add `opacity: .25;` that solves the issue. https://a.supportally.com/i/vO42FW

**Comment by kkarpieszuk** [comment]
good idea, changed

**Comment by kkarpieszuk** [comment]
p.s. anything more @mattbrett ?

**Review by AndriiSmith — APPROVED** [review]
@kkarpieszuk Good job, thank you! 
PR LGTM 👍

**Comment by mattbrett** [comment]
@kkarpieszuk Nope, everything looks good! 🚀

**Pull request merged**
